name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  install:
    name: Install packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/pnpm

  library_prettier:
    name: Run Prettier in library
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/pnpm
      - name: Prettier check
        run: pnpm format.check
        working-directory: library

  library_eslint:
    name: Run ESLint in library
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/pnpm
      - name: ESLint check
        run: pnpm lint
        working-directory: library

  library_vitest:
    name: Run Vitest in library
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/pnpm
      - name: Vitest tests
        run: pnpm test
        working-directory: library

  website_prettier:
    name: Run Prettier in website
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/pnpm
      - name: Prettier check
        run: pnpm format.check
        working-directory: website

  website_eslint:
    name: Run ESLint in website
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/pnpm
      - name: ESLint check
        run: pnpm lint
        working-directory: website
